### ISSUE TITLE
频道申请收录

### ISSUE THREAD

**Issue by ddgksf2013** [jackhawks/rectg#17]
Cuttlefishの自留地

https://t.me/ddgksf2021

分享一些互联网、羊毛、破解IPA及 QX 脚本资源

**Comment by yaoleifly** [comment]
小声读书是一个探索数字阅读可能性和未来的开放项目，致力于打破信息茧房，挖掘价值信息。亦是一份杂志，一个博客，混搭不拘一格，时常荒腔走板。（关注数 29477）

https://t.me/weekly_books

**Comment by 410050753** [comment]
英语/学习/资源宝库【EnglishVault】
https://t.me/wuwuwuEnglish
本频道主要分享安利个人觉得有意思和精致的英语学习资源，希望在英语学习的路上与大家共同进步！！！

**Comment by amu263** [comment]
Amu的音乐，小说，漫画分享小屋
https://t.me/AmuMusicHouse
amu啥都有的资源分享频道，主要分享主观审美喜欢的音乐、推理向小说、漫画资源，欢迎加入一起讨论交流

**Comment by abcmiao** [comment]
APP喵：阿喵软件资源共享
https://t.me/appmew

分享好用软件，优质资源，网站，极客，教程，网络黑科技

**Comment by jackhawks** [comment]
已收录
