### ISSUE TITLE
机器人申请收录

### ISSUE THREAD

**Issue by jackzzs** [jackhawks/rectg#21]
**频道、群组或机器人的链接**
https://t.me/anonyabbot

**频道、群组或机器人的简介**
Anonycnbot 是一个用于创建完全匿名群组的机器人.
1. 创建的匿名群组会以机器人的形式存在, 所有人的消息都将向所有成员广播.
2. 所有身份信息都会被隐藏, 包括姓名、用户名、头像、在线状态、输入状态等等, 用户之间会通过一个Emoji面具区分.
3. 内置了群管理工具, 比如封禁、欢迎消息、置顶消息等等.
4. 仅存储消息ID, 消息内容将不会被存储, 充分考虑隐私性.
5. 开源于: https://github.com/anonyabbot/anonyabbot

暂不收录以下分类的频道、群组和机器人：
1.NSFW、机场、Gaming、Sex、流量卡、手机卡、Politics、索引、导航、地区、推广、海外招聘。
2.没有什么实质内容，纯粹拉人头的。

**Comment by jackhawks** [comment]
已收录
