### ISSUE TITLE
自荐一个技术频道

### ISSUE THREAD

**Issue by chinesehuazhou** [jackhawks/rectg#26]
**频道、群组或机器人的链接**
例如：https://t.me/pythontrendingweekly

**频道、群组或机器人的简介**
例如：为你挑选最值得分享的文章、教程、开源项目、软件工具、播客和视频、热门话题等内容。

暂不收录以下分类的频道、群组和机器人：
1.NSFW、机场、Gaming、Sex、流量卡、手机卡、Politics、索引、导航、地区、推广、海外招聘。
2.没有什么实质内容，纯粹拉人头的。

**Comment by abcmiao** [comment]
APP喵：阿喵软件资源共享
https://t.me/appmew

分享好用软件，优质资源，网站，极客，教程，网络黑科技

**Comment by jackhawks** [comment]
已收录
